services:
  jupyterlab:
    networks:
      - ollama-docker
    depends_on:
      - ollama
    build:
      context: .
      dockerfile: jupyter.Dockerfile
    container_name: jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter:/home/joyvan/work # Mount your local 'work' directory into the container
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=${JUPYTER_TOKEN?JUPYTER_TOKEN}
    working_dir: /home/joyvan/work
